### ISSUE TITLE
add torrent issue

### ISSUE THREAD

**Issue by Mickaelh51** [ValentinGot/real-debrid#3]
Bonjour,
je tente de pousser un torrent pour le télécharger avec le chemin du torrent, le hoster '1' (uptobox.com), et un split de 50Go.
`$torrent = json_encode($realDebrid->torrents->addTorrent($file,1,50));`
Malheureusement j'ai cette erreur:

```
PHP Fatal error:  Uncaught exception 'RealDebrid\Exception\RealDebridException' with message 'Torrent file invalid' in /usr/local/libexec/vendor/vgot/real-debrid/RealDebrid/Exception/ExceptionStatusCodeFactory.php:46
Stack trace:
#0 /usr/local/libexec/vendor/vgot/real-debrid/RealDebrid/Request/AbstractRequest.php(96): RealDebrid\Exception\ExceptionStatusCodeFactory::create(Object(GuzzleHttp\Psr7\Response))
#1 /usr/local/libexec/vendor/vgot/real-debrid/RealDebrid/Api/EndPoint.php(55): RealDebrid\Request\AbstractRequest->make(Object(GuzzleHttp\Client), NULL)
#2 /usr/local/libexec/vendor/vgot/real-debrid/RealDebrid/Api/Torrents.php(67): RealDebrid\Api\EndPoint->request(Object(RealDebrid\Request\Torrents\AddTorrentRequest))
#3 /usr/local/libexec/test_mika_.php(54): RealDebrid\Api\Torrents->addTorrent('/media/download...', 1, 50)
#4 /usr/local/libexec/test_mika_.php(19): add_torrent_to_download(Object(RealDebrid\RealDebrid))
#5 {main}
  thrown in /usr/local/libexec/vendor/vgot/real-debrid/RealDebrid/Exception/ExceptionStatusCodeFactory.php on line 46
```

Y-a-t'il une erreur ? comment puis-je choisir uptobox.com plutôt que 1fichier.com ?

Merci d'avance

**Comment by ValentinGot** [comment]
Bonjour Mickael,

Cette erreur provient de l'API Real-Debrid, elle signifie juste que ton fichier torrent n'est pas valide. Si tu essais de l'ajouter directement sur Real-Debrid, il ne devrait pas fonctionner non plus.
[API error codes](http://api.real-debrid.com/#api_error_codes) => Code d'erreur 30

Par contre, concernant le choix d'uptobox et du split, l'API Real-Debrid ne fonctionne pas encore très bien avec ça. Donc c'est normal si ça ne marche pas.
J'attend les corrections :)

**Comment by Mickaelh51** [comment]
Merci beaucoup pour ta réponse.

je confirme que le fichier torrent est valide, quand je l'importe directement dans real-debrid cela fonctionne. En fait, quand je mets 
`addTorrent($file,1,50)`

Le script explique en effet que le 'torrent file is invalid'.

Mais la même commande avec le même fichier, mais avec 0 à la place de 1
 `addTorrent($file,0,50)`

Cela fonctionne.
Enfin presque ;)
Il pousse le torrent sur RD, RD le télécharge, mais dans l'interface graphique de RD le filename est vide.
1. En haut le torrent file poussé avec l'API
2. En bas, le même torrent file poussé dans l'interface de RD

![screenshot-real-debrid com 2016-01-31 19-07-16](https://cloud.githubusercontent.com/assets/9885404/12703880/51215b52-c84e-11e5-8d15-45ccda7c9ab5.png)

**Comment by ValentinGot** [comment]
C'est un autre problème de l'API RD, je leurs est aussi pausé la question ;)
Mais, en effet, quand on utilise la méthode selectFiles, le filename se retrouve toujours vide à moins que le torrent n'est déjà été uploadé auparavant..

**Comment by Mickaelh51** [comment]
OK ça me rassure ;)
bon je continue, je te remonterai les autres problèmes éventuels si tu le souhaites.

encore merci et bon boulot !

++

**Comment by ValentinGot** [comment]
Pas de problème, merci =)

**Comment by TheCrach** [comment]
Pour le problème de sélection de l'hébergeur c'est très simple, l'hébergeur est demandé en string, pas en int.

**Comment by TheCrach** [comment]
Problème de nom de fichier vide réglé

**Comment by ValentinGot** [comment]
Merci, le problème de nom de fichier vide semble bien avoir réglé.

Par contre le fait de mettre host à "uptobox.com" ne semble pas vouloir fonctionner :s

**Comment by dansleboby** [comment]
Bonjour, je viens de faire usage de l'api et moi j'ai encore le problème du nom de fichier vide.
Quand je fais un print_r de $realDebrid->torrents->torrent("XXXXXXXXXXXXX")
J'obtiens ceci:

```
stdClass Object
(
    [id] => XXXXXXXXXXXXX
    [filename] =>
    [original_filename] => MON NOM DE FICHIER ORIGINALE
    [hash] => 0000xxxx0000xxxx0000xxxx0000xxxx0000
    [bytes] => 0
    [original_bytes] => 999999999
    [host] => real-debrid.com
    [split] => 250
    [progress] => 100
    [status] => downloaded
    [added] => 2016-11-29T07:34:39.000Z
    [files] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 1
                    [path] => /PREMIER FICHIER DANS LE TORRENT
                    [bytes] => 999999999
                    [selected] => 1
                )

            [1] => stdClass Object
                (
                    [id] => 2
                    [path] => /DEUXIÈME FICHIER DANS LE TORRENT
                    [bytes] => 999999999
                    [selected] => 1
                )

        )

    [links] => Array
        (
            [0] => https://real-debrid.com/d/XXXXXXXXXXX
        )

    [ended] => 2016-11-29T07:55:54.000Z
)
```

J'ai masqué certains éléments mais j'ai le bon data au endroit que c'est masquée.


Pour envoyer le fichier je fais:
```php
$realDebrid->torrents->addTorrent($path)->id;
$realDebrid->torrents->selectFiles($torrent_id);
```
Le torrents part bien et tout mais le nom de fichier demeure vide

Merci de votre aide
